### ISSUE TITLE
P50_author/P2093_author_name_string qualifiers

### ISSUE THREAD

**Issue by VladimirAlexiev** [shexSpec/schemas#1]
https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L19
```
   (p:P50 @<P50_author>* | p:P2093 @<P2093_author_name_string>*)+ ;
```
@andrawaag: can you add an example of using a prop as a qualifier, eg [P1545 series ordinal](https://www.wikidata.org/wiki/Property:P1545)

**Comment by emulatingkat** [comment]
@VladimirAlexiev I added an example:

https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L20
and
https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L254

Is this a useful example for your purpose?

**Comment by VladimirAlexiev** [comment]
No because the qualifier should be used inside author/author_names.

**Comment by VladimirAlexiev** [comment]
I think these are good examples:
- https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L68
- https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L209

I wasn't sure they can be used this way, but after examining https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L19 I think they do. However, I think "series ordinal" should be made optional and the data type concretized:
```ttl
pq:P1545 xsd:string?
```

https://github.com/shexSpec/schemas/blob/master/Wikidata/wikicite/wikicite_scholarly_article.shex#L254 should be deleted.

**Comment by andrawaag** [comment]
I agree with your comments here. I took the liberty to make the changes accordingly.
